### ISSUE TITLE
64Bit Support 

### ISSUE THREAD

**Issue by ghost** [adrianopaladini/brightness#1]
Hey there,

thank's for this great module! Starting at February 1st, all apps need to have 64Bit support, which is resolved by the latest 3.5.0 Ti-SDK. 

This also requires all modules to be re-build. So it would be nice to have this module rebuilt to support the latest SDK version. Thank you!

**Comment by adrianopaladini** [comment]
Hi, in this weekend i'll upgrade all my modules.

**Comment by adrianopaladini** [comment]
New version in 64-bit released
