### ISSUE TITLE
Module not shown?

### ISSUE THREAD

**Issue by PietroGranati** [adrianopaladini/brightness#2]
I've imported the modules in titanium like any other, but the android module isn't showed when I try to add it to the app

What's wrong?

**Comment by PietroGranati** [comment]
I've tryed to force insert module in xml and Appcelerator says that this module does not support android :/ please fix!

**Comment by jakis39** [comment]
I'm having the same problem.

**Comment by jakis39** [comment]
Tried recompiling the Android version from source, but it still doesn't work. For now I'm using the old Android version 1.0 from this commit: [f22516f](https://github.com/adrianopaladini/brightness/tree/f22516f81cee8640416bd177554769d02c7b5f16) and it seems to be working for what I need it for. Hope this helps anyone else who comes here.

**Comment by PietroGranati** [comment]
@jakis39 thank you I will try that, just copy it to the modules folder?

**Comment by jakis39** [comment]
I downloaded the source for 1.0 and published it into my app

**Comment by PietroGranati** [comment]
@jakis39 What does it mean published it into my app? put the files?

**Comment by jakis39** [comment]
I mean compile the source code and put the compiled module into your app.

**Comment by PietroGranati** [comment]
@jakis39 thank you, I've never done it so I need to find a guide for build a module

**Comment by PietroGranati** [comment]
@jakis39 Can you send me the compiled version?

**Comment by jakis39** [comment]
I can't attach a zip file to this post.

### To compile the module:
- Download the source from my link above. 
- In Titanium studio, go to File > Import... > Existing Mobile Project
- Select the 'android' folder from the file you just downloaded as the project directory. 
- Titanium should deduce the project name to be 'brightness'. Click Finish.
- You will need to edit the build.properties file under the android project folder to reflect the file paths on your system. 
- Right click the project, go to Publish > Package - Android Module, and select the project to package it into.

**Comment by PietroGranati** [comment]
@jakis39 I'm trying doing it via command-line but seems I need to install some components.
I'll try you guide now, if you can send me the zip to pietro.granati@libemax.com it will be a pleasure.
Thank you for the support @jakis39 !!!

**Comment by PietroGranati** [comment]
@jakis39 Because after compiling and added to project got this error:
failed: dlopen failed: cannot locate symbol "__exidx_end" referenced by "libcom.widbook.brightness.so

**Comment by PietroGranati** [comment]
RESOLVED - Need to build with SDK 4+

**Comment by Sofianio** [comment]
I'm having the same pb, @PietroGranati  plz specify what was "resolved" the v1 or v2?

**Comment by PietroGranati** [comment]
@Sofianio the v1!

**Comment by hansemannn** [comment]
Recompiled with 5.5.1.GA in #4
