### ISSUE TITLE
Module not work with android 6+

### ISSUE THREAD

**Issue by PietroGranati** [adrianopaladini/brightness#3]
Module brightness not work with android 6, so, I've took the source code of the v1 "com.widbook.brightness" and rebuild it with sdk 5.4.0.

It works, just remember to change the require method to match the module

here it is
http://www.mediafire.com/download/nupmsh0ph56l8sr/com.widbook.brightness-android-1.5.zip

**Comment by hansemannn** [comment]
Fixed with #4
